<script src="http://code.jquery.com/jquery-latest.js"></script>

<script language="javascript" type="text/javascript">
var jqnctop = jQuery.noConflict();
jqnctop(document).ready(function(){
	jqnctop('a[name=slidetotop]').slideto({
		target : '#pagetop',
		speed  : 700
	});
});
$(window).scroll(function(){
	if($(window).scrollTop() > 200 ){
		$('#backtotop').fadeIn("slow");
	} else if($(window).scrollTop() < 200 ){
		$('#backtotop').fadeOut("fast");
	}
});
</script>
<!-- SLIDING BACK TO TOP -->
<script language="javascript" type="text/javascript">
$(function() {
	// HIGHLIGHT TEXTBOX BORDER ON FOCUS AND HIDE ON BLUR
	$("input").focus(function() {
		$(this).addClass("curFocus");
	});
	$("input").blur(function() {
		$(this).removeClass("curFocus")
	});

	$("textarea").focus(function() {
		$(this).addClass("curFocusTextarea");
	});
	$("textarea").blur(function() {
		$(this).removeClass("curFocusTextarea")
	});

	$("select").focus(function() {
		$(this).addClass("curFocus");
	});
	$("select").blur(function() {
		$(this).removeClass("curFocus")
	});
	// HIGHLIGHT TEXTBOX BORDER ON FOCUS AND HIDE ON BLUR
	
	// MOVE LEFT SIDE ICONS ON HOVER
	$("div.sticky-left").hover(function(){
		$(this).animate({
			left: "4px"
		},"fast");
	},function(){
		$(this).animate({
			left: "2px"
		},"fast");
	});
	// MOVE LEFT SIDE ICONS ON HOVER
});
</script>
<script language="javascript" type="text/javascript" src="<?php echo BASE_URL.'js/functions.js?1379088342'?>"></script>
<script type="text/javascript" src="<?php echo BASE_URL.'js/browser_check.js'?>"></script>
<script type="text/javascript" src="<?php echo BASE_URL.'js/smooth.pack.js'?>"></script>

<!-- BEGIN INCLUDE SCRIPTS TO CALL SHADOWBOX -->

<script type="text/javascript" src="<?php echo BASE_URL.'js/shadowbox/shadowbox.js'?>"></script>
<script type="text/javascript" src="<?php echo BASE_URL.'js/shadowbox/show_shadowbox.js'?>"></script>
<!-- END INCLUDE SCRIPTS TO CALL SHADOWBOX -->

<!-- DROPDOWN CONTENT FOR MY GROUP OPTIONS -->
<script type="text/javascript" src="<?php echo BASE_URL.'js/dropdowncontent/dropdowncontent.js'?>"></script>
<!-- DROPDOWN CONTENT FOR MY GROUP OPTIONS -->

<!-- DROPDOWN TOP MENU -->
<script type="text/javascript" src="<?php echo BASE_URL.'js/dropdowntab/dropdowntabs.js'?>"></script>
<!-- DROPDOWN TOP MENU -->

<!-- BEGIN INCLUDE SCRIPTS TO CALL DHTML TOOLTIP -->
<link rel="stylesheet" type="text/css" href="<?php echo BASE_URL.'css/speechbubbles.css'?>" />
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js"></script>
<script src="<?php echo BASE_URL.'js/speechbubbles.js'?>"></script>

<!-- BEGIN INCLUDE SCRIPTS FOR TABBED CONTENT FOR INVITE TABS -->
<link rel="stylesheet" type="text/css" href="<?php echo BASE_URL.'css/tabcontent.css'?>" />
<script type="text/javascript" src="<?php echo BASE_URL.'js/tabcontent.js'?>"></script>
<!-- BEGIN INCLUDE SCRIPTS FOR TABBED CONTENT FOR INVITE TABS -->
<!-- SLIDING FOOTER FUNCTION -->
<script language="javascript" type="text/javascript">
$(function() {
	var open = false;
	$('#footerSlideButton').click(function() {
		if(open === false) {
			document.getElementById('footerSlideText').style.display='block';
			$('#footerSlideContent').animate({ height: '50px' });
			$(this).css('backgroundPosition', 'bottom left');
			open = true;
		} else {
			document.getElementById('footerSlideText').style.display='none';
			$('#footerSlideContent').animate({ height: '0px' });
			$(this).css('backgroundPosition', 'top left');
			open = false;
		}
	});
});
</script>
<!-- SLIDING FOOTER FUNCTION -->
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<link rel="stylesheet" href="<?php echo BASE_URL.'css/styles-index.css'?>" type="text/css" />
<link rel="stylesheet" href="<?php echo BASE_URL.'css/styles.css'?>" type="text/css" />
<script type="text/javascript">
$(document).ready(function(){
	$("input").focus(function() {

		$(this).addClass("curFocus");

	});
	$("input").blur(function() {

		$(this).removeClass("curFocus")

	});
});
</script>

<link rel="stylesheet" href="<?php echo BASE_URL.'css/whitebg.css'?>" type="text/css" />

<style type="text/css">
element.style {
    float: left;
    margin-bottom: 20px;
    margin-left: 10px;
    margin-top: 10px;
}
</style>
<link rel="stylesheet" type="text/css" href="<?php echo BASE_URL.'css/style.css'?>" />
<script type="text/javascript" src="<?php echo BASE_URL.'js/functions.js'?>"></script>
<?php
 //echo BASE_URL.'js/functions.js'; 
//echo $this->headLink()->appendStylesheet($this->baseUrl().'/css/style.css')->appendStylesheet($this->baseUrl().'/css/common.css');*/
echo $this->headScript()->appendFile(BASE_URL.'js/browser_check.js'); 
?>
<div>
		<form name="signupform" id="signupform" action="signupmessage" method="post">
		   <p><strong>Enter the code below</strong></p>
			 <?php echo $this->form ; ?>
			 <div id="signuperror"></div>
			<p></p><div class="button" style="margin-top:10px; font-size:12px" onclick="javascript:document.getElementById('signuperror').style.display='none';document.signupform.submit();">complete signup</div><p></p>
			<input id="user" name="user" value="14531" type="hidden">
		</form>
</div>