<?php echo $this->doctype() ?>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />

<title>dbee.me | the debate n rate social network</title>

<meta name="description" content="dbee is a real time 'debate and rate' social network enabling you to share views on any subject, in open community or closed groups. Create debate by posting opinions, photos, videos and links, score and be scored on posts, and rise or fall in dbee leagues.">

<meta property="og:url" content="http://www.dbee.me.com" /> 

<meta property="og:type" content="article" /> 

<meta property="og:title" content="dbee.me | the debate n rate social network" /> 

<meta property="og:site_name" content="dbee" /> 

<meta property="og:description" content="dbee is a real time 'debate and rate' social network enabling you to share views on any subject, in open community or closed groups. Create debate by posting opinions, photos, videos and links, score and be scored on posts, and rise or fall in dbee leagues." /> 

<meta property="og:image" content="http://www.dbee.me/images/landing-logo.png" />

<link rel="icon" type="image/png" href="http://dbee.me/images/favicon.png">



<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => 'http://dbee.me/images/favicon.png'))

                       // ->prependStylesheet(BASE_URL . '/css/bootstrap-responsive.min.css')

                        ->prependStylesheet(BASE_URL . '/css/style.css')

                        ->prependStylesheet(BASE_URL . '/css/global.css')

                       // ->prependStylesheet(BASE_URL . '/css/bootstrap.min.css')

						->prependStylesheet(BASE_URL . '/css/speechbubbles.css')					

						->prependStylesheet(BASE_URL . '/css/ddcolortabs.css')					

						->prependStylesheet(BASE_URL . '/css/tabcontent.css')

						->prependStylesheet(BASE_URL . '/css/styles.css')

						->prependStylesheet(BASE_URL . '/css/dbee.css')						

						->prependStylesheet(BASE_URL . '/css/jquery.css')

						->prependStylesheet(BASE_URL . '/css/jquery.blockUI.css')

						->prependStylesheet(BASE_URL . '/css/shadowbox.css')

						->prependStylesheet(BASE_URL . '/css/dbee.css')						

						?>

<!-- Scripts -->

<?php echo $this->headScript()->prependFile(BASE_URL . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))

                     // ->prependFile(BASE_URL . '/js/bootstrap.min.js')

					  ->prependFile(BASE_URL . '/js/smooth.pack.js')

                      ->prependFile(BASE_URL . '/js/jquery.min.js')

				      ->prependFile(BASE_URL . '/js/functions.js')

				      ->prependFile(BASE_URL . '/js/browser_check.js')

				      ->prependFile(BASE_URL . '/js/ajaxupload.js')

				      ->prependFile(BASE_URL . '/js/jquery-latest.js')

				      ->prependFile(BASE_URL . '/js/jquery.min_1.4.4.js')

				      ->prependFile(BASE_URL . '/js/jquery.min_1.4.js')

				      ->prependFile(BASE_URL . '/js/jquery.slideto.v1.1.js')	

				      //->prependFile(BASE_URL . '/js/shadowbox/show_shadowbox.js')

				      //->prependFile(BASE_URL . '/js/shadowbox/shadowbox.js')				      

				      ->prependFile(BASE_URL . '/js/all.js')				

				      ->prependFile(BASE_URL . '/js/ddaccordion.js')

				      ->prependFile(BASE_URL . '/js/dropdowncontent.js')

				      ->prependFile(BASE_URL . '/js/dropdowntabs.js')	

				      ->prependFile(BASE_URL . '/js/html5.js')

				      ->prependFile(BASE_URL . '/js/javascript.js')

				      ->prependFile(BASE_URL . '/js/jquery.blockUI.js')

				      ->prependFile(BASE_URL . '/js/tabcontent.js')

				      ->prependFile(BASE_URL . '/js/speechbubbles.js')

				      ->prependFile(BASE_URL . '/js/jquery.js')

				    				   

				      ?>







<script language="javascript" type="text/javascript">

var screenwidth = screen.width;

if (screenwidth == 1024) {

	document.write('<link rel="stylesheet" href="<?php echo BASE_URL.'css/1024.css'?>" type="text/css" media="all" />');

}

</script>





<script language="javascript" type="text/javascript" src="<?php echo BASE_URL.'js/functions.js?1379088342'?>"></script>

<script type="text/javascript" src="<?php echo BASE_URL.'js/browser_check.js'?>"></script>

<script type="text/javascript" src="<?php echo BASE_URL.'js/smooth.pack.js'?>"></script>



<!-- BEGIN INCLUDE SCRIPTS TO CALL SHADOWBOX -->



<script type="text/javascript" src="<?php echo BASE_URL.'js/shadowbox/shadowbox.js'?>"></script>

<script type="text/javascript" src="<?php echo BASE_URL.'js/shadowbox/show_shadowbox.js'?>"></script>

<!-- END INCLUDE SCRIPTS TO CALL SHADOWBOX -->



<!-- DROPDOWN CONTENT FOR MY GROUP OPTIONS -->

<script type="text/javascript" src="<?php echo BASE_URL.'js/dropdowncontent/dropdowncontent.js'?>"></script>

<!-- DROPDOWN CONTENT FOR MY GROUP OPTIONS -->



<!-- DROPDOWN TOP MENU -->

<script type="text/javascript" src="<?php echo BASE_URL.'js/dropdowntab/dropdowntabs.js'?>"></script>

<!-- DROPDOWN TOP MENU -->



<!-- BEGIN INCLUDE SCRIPTS TO CALL DHTML TOOLTIP -->

<link rel="stylesheet" type="text/css" href="<?php echo BASE_URL.'css/speechbubbles.css'?>" />

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js"></script>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js"></script>

<script src="<?php echo BASE_URL.'js/speechbubbles.js'?>"></script>

<script type="text/javascript">

jQuery(function($){ //on document.ready

 $('.addspeech').speechbubble()

})

</script>

<script type="text/javascript" src="<?php echo BASE_URL.'scripts/ajaxupload.js'?>"></script>

<script src="http://code.jquery.com/jquery-latest.js"></script>

<!-- SLIDING BACK TO TOP -->

<script language="javascript" type="text/javascript" src="<?php echo BASE_URL.'js/jquery.slideto.v1.1.js'?>"></script>

<script language="javascript" type="text/javascript">

var jqnctop = jQuery.noConflict();

jqnctop(document).ready(function(){

	jqnctop('a[name=slidetotop]').slideto({

		target : '#pagetop',

		speed  : 700

	});

});



$(window).scroll(function(){

	if($(window).scrollTop() > 200 ){

		$('#backtotop').fadeIn("slow");

	} else if($(window).scrollTop() < 200 ){

		$('#backtotop').fadeOut("fast");

	}

});

</script>

<script language="javascript" type="text/javascript">

$(function() {

	// HIGHLIGHT TEXTBOX BORDER ON FOCUS AND HIDE ON BLUR

	$("input").focus(function() {

		$(this).addClass("curFocus");

	});

	$("input").blur(function() {

		$(this).removeClass("curFocus")

	});



	$("textarea").focus(function() {

		$(this).addClass("curFocusTextarea");

	});

	$("textarea").blur(function() {

		$(this).removeClass("curFocusTextarea")

	});



	$("select").focus(function() {

		$(this).addClass("curFocus");

	});

	$("select").blur(function() {

		$(this).removeClass("curFocus")

	});

	// HIGHLIGHT TEXTBOX BORDER ON FOCUS AND HIDE ON BLUR

	

	// MOVE LEFT SIDE ICONS ON HOVER

	$("div.sticky-left").hover(function(){

		$(this).animate({

			left: "4px"

		},"fast");

	},function(){

		$(this).animate({

			left: "2px"

		},"fast");

	});

	// MOVE LEFT SIDE ICONS ON HOVER

});

</script>

<link rel="stylesheet" type="text/css" href="<?php echo BASE_URL.'css/tabcontent.css'?>" />

<script type="text/javascript" src="<?php echo BASE_URL.'js/tabcontent.js'?>"></script>

<script language="javascript" type="text/javascript">

$(function() {

	var open = false;

	$('#footerSlideButton').click(function() {

		if(open === false) {

			document.getElementById('footerSlideText').style.display='block';

			$('#footerSlideContent').animate({ height: '50px' });

			$(this).css('backgroundPosition', 'bottom left');

			open = true;

		} else {

			document.getElementById('footerSlideText').style.display='none';

			$('#footerSlideContent').animate({ height: '0px' });

			$(this).css('backgroundPosition', 'top left');

			open = false;

		}

	});

});

</script>

<script type="text/javascript">

$(document).ready(function(){

	$("input").focus(function() {

		$(this).addClass("curFocus");

	});

	$("input").blur(function() {

		$(this).removeClass("curFocus")

	});

});
</script>

<style type="text/css">
body {background-color:#FFFFFF}
</style>
<link rel="stylesheet" href="<?php echo BASE_URL.'css/whitebg.css'?>" type="text/css" />
</head>
<body>
<div style="clear:both"></div>
<!---------end header---------------------------->
<style type="text/css">
.style3 {	font-size: 12px;
	font-weight: bold;
}
body {
	margin-left: 0px;
	margin-top: 0px;
	margin-right: 0px;
	margin-bottom: 0px;
	background-color: #FFFFFF;
}
</style>
<?php 
$storage 	= new Zend_Auth_Storage_Session();
$data	  	= $storage->read();
//echo'<pre>';print_r($data['UserID']);
?>
<div id="signuplastWrapper">
  <div class="style3" style="padding:10px; background-color:#C2BEBC">deactivate my account</div>
  <div id="confirmclose" align="center" style="padding:10px; font-size:16px">
    <p>Are you sure you want to deactivate your account?</p>
    <p><a href="javascript:closeaccount(<?php echo $data['UserID']; ?>)">Yes</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="javascript:void(0);" onclick="javascript:parent.Shadowbox.close();">No</a></p>
  </div>

  <div id="closeaccountmessage" align="center" style="padding:10px; display:none;">
 	<p>It's sad to see you go :(</p>
	<p>Your account has been deactivated. You can re-activate your account any time by sending us a request using the link in footer.</p>
  </div>
</div>

