<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta charset="utf-8">
<meta name="description" content="dbee LIFE is a real time 'debate and rate' social network enabling you to share views on any subject, in open community or closed groups. Create debate by posting opinions, photos, videos and links, score and be scored on posts, and rise or fall in dbee leagues.">
<meta property="og:url" content="http://www.dbeelife.com" />
<meta property="og:type" content="article" />
<meta property="og:title" content="dbee LIFE - Create Debate" />
<meta property="og:site_name" content="dbee LIFE" />
<meta property="og:description" content="dbee LIFE is a real time 'debate and rate' social network enabling you to share views on any subject, in open community or closed groups. Create debate by posting opinions, photos, videos and links, score and be scored on posts, and rise or fall in dbee leagues." />
<meta property="og:image" content="http://www.dbeelife.com/images/landing-logo.png" />
<?php echo $this->headTitle('dbee.me  '. $this->translate('the debate n rate social network'))->setSeparator(' | ')->setAutoEscape(false) ?><?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
<title> | the debate n rate social network</title>
<link rel="icon" type="image/png" href="http://dbee.me/images/favicon.png">
<meta name="robots" content="noindex">
<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => 'http://dbee.me/images/favicon.png'))
                       // ->prependStylesheet(BASE_URL . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet(BASE_URL . '/css/style.css')
                        ->prependStylesheet(BASE_URL . '/css/global.css')
                       // ->prependStylesheet(BASE_URL . '/css/bootstrap.min.css')
						->prependStylesheet(BASE_URL . '/css/speechbubbles.css')					
						->prependStylesheet(BASE_URL . '/css/ddcolortabs.css')					
						->prependStylesheet(BASE_URL . '/css/tabcontent.css')
						->prependStylesheet(BASE_URL . '/css/styles.css')
						->prependStylesheet(BASE_URL . '/css/dbee.css')						
						->prependStylesheet(BASE_URL . '/css/jquery.css')
						->prependStylesheet(BASE_URL . '/css/jquery.blockUI.css')
						->prependStylesheet(BASE_URL . '/css/shadowbox.css')
						->prependStylesheet(BASE_URL . '/css/tooltip.css')
						->prependStylesheet(BASE_URL . '/css/dbee.css')
						->prependStylesheet(BASE_URL . '/css/jquery.autocomplete.css')							
						?>
<!-- Scripts -->
<?php echo $this->headScript()->prependFile(BASE_URL . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                     // ->prependFile(BASE_URL . '/js/bootstrap.min.js')
					  ->prependFile(BASE_URL . '/js/smooth.pack.js')
                      ->prependFile(BASE_URL . '/js/jquery.min.js')
				      ->prependFile(BASE_URL . '/js/functions.js')
				      ->prependFile(BASE_URL . '/js/browser_check.js')
				      ->prependFile(BASE_URL . '/js/ajaxupload.js')
				      ->prependFile(BASE_URL . '/js/jquery-latest.js')
				      ->prependFile(BASE_URL . '/js/jquery.min_1.4.4.js')
				      ->prependFile(BASE_URL . '/js/jquery.min_1.4.js')
				      ->prependFile(BASE_URL . '/js/jquery.slideto.v1.1.js')	
				      ->prependFile(BASE_URL . '/js/shadowbox/show_shadowbox.js')
				      ->prependFile(BASE_URL . '/js/shadowbox/shadowbox.js')
				      ->prependFile(BASE_URL . '/js/qtip/jquery.qtip-1.0.0-rc3.min.js')
				      ->prependFile(BASE_URL . '/js/qtip/jquery-1.3.2.min.js')
				      ->prependFile(BASE_URL . '/js/all.js')				      
				      ->prependFile(BASE_URL . '/js/ddaccordion.js')
				      ->prependFile(BASE_URL . '/js/dropdowncontent.js')
				      ->prependFile(BASE_URL . '/js/dropdowntabs.js')
					  ->prependFile(BASE_URL . '/js/autocomplete/jquery.js')
					  ->prependFile(BASE_URL . '/js/autocomplete/jquery.autocomplete.js')				 				  
				      ->prependFile(BASE_URL . '/js/html5.js')
				      ->prependFile(BASE_URL . '/js/javascript.js')
				      ->prependFile(BASE_URL . '/js/jquery.blockUI.js')
				      ->prependFile(BASE_URL . '/js/tabcontent.js')
				      ->prependFile(BASE_URL . '/js/speechbubbles.js')
				      ->prependFile(BASE_URL . '/js/jquery.js')
				    				   
				      ?>				     
<?php 
//////////mytop start///////
//echo $this->render('layout/top');
//////////mytop end///////
echo $this->content; ?>
<script src="http://code.jquery.com/jquery-latest.js"></script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.0/jquery.min.js"></script>

<script type="text/javascript">
jQuery(function($){ //on document.ready
 //$('.addspeech').speechbubble()
})
</script>				     	      
<script language="javascript" type="text/javascript">
var jqnctop = jQuery.noConflict();
jqnctop(document).ready(function(){
	jqnctop('a[name=slidetotop]').slideto({
		target : '#pagetop',
		speed  : 700
	});
});

$(window).scroll(function(){
	if($(window).scrollTop() > 200 ){
		$('#backtotop').fadeIn("slow");
	} else if($(window).scrollTop() < 200 ){
		$('#backtotop').fadeOut("fast");
	}
});
</script>
<script type="text/javascript">
<? if(isset($_GET['err']) || isset($_GET['close'])) { $accmsg=(isset($_GET['err'])) ? '<div class="login-err">Incorrect login details.<br /><br />Please login again.</div>' : '<div class="login-err">This account is closed.<br /><br />Please signup again.</div>'; ?>
window.onload = function() {
    // open a welcome message as soon as the window loads
    Shadowbox.open({
        content:    <?=$accmsg?>,
        player:     "html",
        title:      "",
        height:     90,
        width:      300
    });
};

setTimeout("parent.Shadowbox.close()",4000);
<? } ?>
</script>
<script language="javascript" type="text/javascript">
var screenwidth = screen.width;
if (screenwidth == 1024) {
	document.write('<link rel="stylesheet" href="css/1024.css" type="text/css" media="all" />');
}
</script>

<script type="text/javascript" src="js/ddaccordion.js">
/***********************************************
* Accordion Content script- (c) Dynamic Drive DHTML code library (www.dynamicdrive.com)
* Visit http://www.dynamicDrive.com for hundreds of DHTML scripts
* This notice must stay intact for legal use
***********************************************/
</script>

<style type="text/css">
.accordion {
	cursor: hand;
	cursor: pointer;
	color:#000000;
	width:180px;
	padding:10px;
	background-color:#FFFA7F;
	border:1px solid #FFEA00;

	-webkit-box-shadow: 0px 0px 3px #999;
	-moz-box-shadow: 0px 0px 3px #999;
	box-shadow: 0px 0px 3px #999;

	-webkit-border-radius: 3px;
	-moz-border-radius: 3px;
	border-radius: 3px;
	margin-bottom:10px;
/*
	-ms-filter:"progid:DXImageTransform.Microsoft.Alpha(Opacity=70)";
	filter:alpha(opacity=70);
	opacity:0.7;
*/
}

.accordionopen {
	color:#999999;
/*
	-ms-filter:"progid:DXImageTransform.Microsoft.Alpha(Opacity=100)";
	filter:alpha(opacity=100);
	opacity:1;
*/
}

.accordioncontent {
	padding:10px;
}
</style>

<script type="text/javascript">
//Initialize Accordion
ddaccordion.init({
	headerclass: "accordion", //Shared CSS class name of headers group
	contentclass: "accordioncontent", //Shared CSS class name of contents group
	revealtype: "click", //Reveal content when user clicks or onmouseover the header? Valid value: "click" or "mouseover"
	mouseoverdelay: 300, //if revealtype="mouseover", set delay in milliseconds before header expands onMouseover
	collapseprev: true, //Collapse previous content (so only one open at any time)? true/false 
	defaultexpanded: [0], //index of content(s) open by default [index1, index2, etc]
	onemustopen: false, //Specify whether at least one header should be open always (so never all headers closed)
	animatedefault: false, //Should contents open by default be animated into view?
	persiststate: false, //persist state of opened contents within browser session?
	toggleclass: ["", "accordionopen"], //Two CSS classes to be applied to the header when it's collapsed and expanded, respectively ["class1", "class2"]
	togglehtml: ["none", "", ""], //Additional HTML added to the header when it's collapsed and expanded, respectively  ["position", "html1", "html2"] (see docs)
	animatespeed: "500", //speed of animation: "fast", "normal", or "slow"
	oninit:function(expandedindices){ //custom code to run when headers have initalized
		//do nothing
	},
	onopenclose:function(header, index, state, isuseractivated){ //custom code to run whenever a header is opened or closed
		//do nothing
	}
})
</script>

<script language="javascript" type="text/javascript">
function loadrss(myurl,logo,counter) {
document.getElementById('rssfeed-logo').style.display='none';
document.getElementById('rssfeed-wrapper').style.display='none';
document.getElementById('twitter-search-box').style.display='block';

$('#rss0').css({'background-color': '#FFF', 'border': '1px solid #FFF'});
$('#rss1').css({'background-color': '#FFF', 'border': '1px solid #FFF'});
$('#rss2').css({'background-color': '#FFF', 'border': '1px solid #FFF'});
$('#rss3').css({'background-color': '#FFF', 'border': '1px solid #FFF'});
$('#rss4').css({'background-color': '#FFF', 'border': '1px solid #FFF'});
$('#rss'+counter).css({'background-color': '#EFEFEF', 'border': '1px solid #FACE3F'});
}

var DbeeFeedHttp;
function dbeefeedresult()
{
if(DbeeFeedHttp.readyState==4)
{
if(DbeeFeedHttp.status == 200 || DbeeFeedHttp.status == 0)
{
var result=DbeeFeedHttp.responseText;
if(result=='1') {
var feedtype=document.getElementById('feedtype').value;
if(feedtype=='all') {
reloadFeeds();
}
}
}
else {}
}
}

</script>
<!-- SLIDING BACK TO TOP -->
<script language="javascript" type="text/javascript">
$(function() {
	// HIGHLIGHT TEXTBOX BORDER ON FOCUS AND HIDE ON BLUR
	$("input").focus(function() {
		$(this).addClass("curFocus");
	});
	$("input").blur(function() {
		$(this).removeClass("curFocus")
	});

	$("textarea").focus(function() {
		$(this).addClass("curFocusTextarea");
	});
	$("textarea").blur(function() {
		$(this).removeClass("curFocusTextarea")
	});

	$("select").focus(function() {
		$(this).addClass("curFocus");
	});
	$("select").blur(function() {
		$(this).removeClass("curFocus")
	});
	// HIGHLIGHT TEXTBOX BORDER ON FOCUS AND HIDE ON BLUR
	
	// MOVE LEFT SIDE ICONS ON HOVER
	$("div.sticky-left").hover(function(){
		$(this).animate({
			left: "4px"
		},"fast");
	},function(){
		$(this).animate({
			left: "2px"
		},"fast");
	});
	// MOVE LEFT SIDE ICONS ON HOVER
});
</script>
<script language="javascript" type="text/javascript">
$(function() {
	var open = false;
	$('#footerSlideButton').click(function() {
		if(open === false) {
			document.getElementById('footerSlideText').style.display='block';
			$('#footerSlideContent').animate({ height: '50px' });
			$(this).css('backgroundPosition', 'bottom left');
			open = true;
		} else {
			document.getElementById('footerSlideText').style.display='none';
			$('#footerSlideContent').animate({ height: '0px' });
			$(this).css('backgroundPosition', 'top left');
			open = false;
		}
	});
});
</script>
